.gitignore, Makefile, benchmark/script/interptime_cufinufft.py, benchmark/script/spreadkernel_cufinufft_breakdown.py, benchmark/script/spreadtime_cufinufft.py
This cleans up the root a little by putting all the compiled binaries (mostly tests) into `bin`. I also modified the Python benchmark scripts to use the new path.
=> Move binaries into bin folder

Makefile
The source has been removed, so we no longer need the target.
=> Remove cufinufft_test target in Makefile

Makefile
Closes #17 .
In #1 I added `clib` to `all`, but forgot to make all the default. This fixes that and adds `.PHONY` for recipe only targets.
=> Update default makefile target

README.md, examples/example2d1many.cpp, examples/example2d2many.cpp, include/cufinufft.h, src/cufinufft.cu, src/cufinufftc.cpp, test/cufinufft2d1_test.cu, test/cufinufft2d1many_test.cu, test/cufinufft2d2_test.cu, test/cufinufft2d2many_test.cu, test/cufinufft3d1_test.cu, test/cufinufft3d2_test.cu, test/interp_2d.cu, test/interp_3d.cu, test/spread_2d.cu, test/spread_3d.cu
Instead of by reference. This will hopefully simplify the interface enough to allow for a unified C and C++ interface once we sort out the pointer stuff.
=> Pass opts by pointer to cufinufft_default_opts

test/cufinufft2d1_test.cu, test/cufinufft2d1many_test.cu, test/cufinufft2d2_test.cu, test/cufinufft2d2many_test.cu, test/cufinufft3d1_test.cu, test/cufinufft3d2_test.cu, test/interp_2d.cu, test/interp_3d.cu, test/spread_2d.cu, test/spread_3d.cu
This is related to ISSUE #19 . 
Places that still use TIME flags are:
- Around calls of cudaMalloc(&a,1). 
The call of this function is no longer needed since we are now excluding the timing of allocating the gpu memory. I will delete the call and also the TIME flags for this part. But since for spread and interpolation only tests, we still allocate the gpu memory during the call of `cufinufft_spread*d` and `cufinufft_interp*d`. I leave the warm up code for those tests but delete the TIME flags around it. 
- Inside cufinufft2d2_test.cu. To be consistent to other tests, we still time the code even if the user doesn't set the TIME flags.
=> removing TIME flags in the test codes. 

contrib/common.cpp, contrib/common.h, contrib/utils.cpp, contrib/utils.h, src/3d/spread3d_wrapper.cu, src/3d/spreadinterp3d.cu, src/cufinufft.cu, test/cufinufft3d1_test.cu, test/cufinufft3d2_test.cu
These commits fix the error when using spreading method 4 in 3D. The method currently only works for size of the transformation being a multiplication of the size of `obin`. I added some checks so that the codes will return error messages when the condition doesn't satisfy. 
Here is an example output:
I set the `obinsize` to (8x8x8) so one can test with size of the transformation being (4Nx4Nx4N), when N being an integer. If the size is not (4Nx4Nx4N), the code will return error.
=> 3d1 blockgather

Makefile
I have been using something like this from my own text file, adjusting it here and there.
@MelodyShih you probably have the best insight into which tests are meaningful (sizes) and would cover (exercise) the most out of your code. I think some of these sizes I wrote down relate to ASPIRE, though the NU points might not. 
Please change it up as you see fit :) Don't be afraid to add run tests, even if they duplicate a little, to exercise your code. These really don't take too long, even on my older cards.
Just having the make check will probably save more time than extra test lines take :).
=> Add a simple collection of run checks to makefile

Jenkinsfile
Library is already build in the Dockerfile, so no need to do it for
Jenkins. Also fix path to Python binary.
=> Remove extra make invocation

python/cufinufft/cufinufft.py, python/cufinufft/tests/test_basic.py
This code tries to ensure that cleanup only occurs ~once~ in the correct order.  The initial `__del__` method wasn't always working correctly atexit from top of file scope (but was working fine in functions etc).
=> Fix tof cleanup

setup.py
When libraries are not found, we can't use lib (since it's not defined).
=> Fix error message in setup.py

Makefile, include/cufinufft_eitherprec.h, include/cufinufft_opts.h, src/2d/interp2d_wrapper.cu, src/2d/spread2d_wrapper.cu, src/3d/interp3d_wrapper.cu, src/3d/spread3d_wrapper.cu, src/cufinufft.cu, src/cuspreadinterp.h, src/memtransfer_wrapper.cu, test/interp2d_test.cu, test/interp3d_test.cu, test/spread2d_test.cu, test/spread3d_test.cu
This pull request is related to #65 .
Here is a list of changes I make:
- Previously, the spread,interp only functions assume x,y,z,c,fw arrays are on cpu. I changed to use gpu array d_x,d_y,d_z,d_c,d_fw as inputs.
- Add an option "gpu_spreadinterponly" so that we don't allocate/free memory for fw and fwkerhalf arrays when calling ALLOCGPUMEMROY{2,3}D_PLAN and FREEGPUMEMORY{2,3}D.
- Make the spread,interp only test codes be compiled for both precision. 
- Checks for valid values of binsizex, binsizey, binsizez.
- Set binsizex, binsizey, binsizez in the spread,interp{2,3}_test.cu. This fixes the error of running `interp_2d`. binsize{x,y} are set to -1 when calling default options and in the spread,interp only function, SET_BINSIZE is not called.
=> Update spread/interp only tests

.bumpversion.cfg, README.md, python/cufinufft/__init__.py, python/cufinufft/cufinufft.py, python/cufinufft/docs/conf.py, python/cufinufft/tests/test_basic.py, python/cufinufft/tests/utils.py, setup.py
Closes #61 . Changes mode shape to default order for numpy's `ndarray.shape` (nZ, nY, nX).
Also establishes bumpversion, and bumps the version from `1.0` to `1.1`.
I have rebuilt v1.1 wheels locally, with this and all the changes from yesterday. I will be testing locally. I can push them to the staging index later if they look okay (this would allow anyone to test them via a pip command).
=> Fpts order

test/cufinufft2d1_test.cu, test/cufinufft2d1many_test.cu, test/cufinufft2d2_test.cu, test/cufinufft2d2many_test.cu, test/cufinufft3d1_test.cu, test/cufinufft3d2_test.cu
It is now calling cufftPlan1d instead of cufftPlanMany. The warmup timings from both functions are similar. Changing this is to avoid giving users an impression that the same cufft plan call is needed.
=> Simplify the dummy cuFFT call

contrib/spreadinterp.cpp
I found that when dividing epsilon by 10, if we don't cast 10.0 to FLT first, kernel width `ns` may not be calculated as expected e.g. for eps=1e-6, ns will be 8 instead of 7.
=> fix calculation of kernel width

src/2d/spreadinterp2d.cu, src/3d/spreadinterp3d.cu
Checks `ix, iy, iz>0` are to ensure that threads won't write into wrong indexes of shared memory. This fixes an error I occurred when running with large number of nonuniform points. There might be a point that has coordinate that lies close to the boundary of the bin and causes negative value of one of the calculated indexes `ix`, `iy` or `iz`. 
There is also minor modification of when to do the check. They are now done so that threads will exit the for loop earlier.
=> Add checks on index bounds for spread kernel

src/2d/spread2d_wrapper_paul.cu, src/3d/cufinufft3d.cu, src/3d/interp3d_wrapper.cu, src/3d/spread3d_wrapper.cu, src/memtransfer_wrapper.cu
The main leak was due to `d_plan->c` being `cudaMalloc`'ed but never `cudaFree`'d if using the python interface. This PR addresses this issue, and adds a few guards against potential memory leaks when the plan gets executed several times without destroying it first.
=> Fix memory leak

python/cufinufft/requirements.txt
The pycuda package depends should probably include it (since it's trying to use it...), but we can also try to ensure it is installed in this case.
This is read by as part of `setup.py` and should install the dependency when cufinufft is installed, just before the pytest lines..  I think :)
=> try adding six here

include/cufinufft_eitherprec.h, src/memtransfer_wrapper.cu, test/cufinufft3d1_test.cu
This commit fixes memory leak mentioned in #75 . The main errors are missing "`break`" in `ALLOCGPUMEM2D_PLAN` for `gpu_method==2` and the allocation of array `numsubprob` for method 1 in both 2,3D.
=> Fix memleak

python/cufinufft/cufinufft.py, python/cufinufft/tests/test_basic.py, python/cufinufft/tests/test_error_checks.py
Summary:
– `set_pts` infers number of points from input
– `tol` and `ntransforms` are now `eps` and `n_trans`
– order of arguments to `cufinufft` and default values are now the same as Finufft
– `opts` is no longer given as an object but is parsed from the kwargs to `cufinufft`
=> Make Python interface closer to FINUFFT

include/cufinufft_opts.h, python/cufinufft/_cufinufft.py, python/cufinufft/cufinufft.py, python/cufinufft/tests/test_error_checks.py, python/cufinufft/tests/test_multi.py, src/cufinufft.cu, src/memtransfer_wrapper.cu
Following the discussing in #67, I implemented some basic multi-GPU support. The strategy with cufinufft has been to:
1. Add a `cuda_device_id` to the `cufinufft_opts` struct
2. All top-level `cufinufft` functions that either take the options (or a copy of the options in the plan) respect this setting:
1. `CUFINUFFT_MAKEPLAN`
2. `CUFINUFFT_SETPTS`
3. `CUFINUFFT_EXECUTE`
4. `CUFINUFFT_DESTROY`
5.  everything in `memtransfer_wrapper.cu`
In theory, we can enable more fine-grained multi-gpu control, but this is more than enough (the `cudaSetDevice` calls in `memtransfer_wrapper.cu` are probably overkill -- but I tend not to take chances with memory) for data-parallel workflows. Here is an example of a data-parallel workflow in python:
```python …
```
=> Add basic multi-gpu support

Jenkinsfile
This is just temporary until the second GPU comes back on.
=> Tell Jenkins to run on one GPU

Makefile, examples/example2d1many.cpp, examples/example2d1many.py, examples/example2d2many.cpp, examples/example2d2many.py, python/cufinufft/tests/test_examples.py
Couldn't get the C++ examples to run at first since they seem to be using the old (struct pointer) interface. It would be good to somehow include the examples in the CI so that we know they're correct at all times.
The Python examples follow the C++ examples more or less, I just changed the parameters slightly.
=> Fix C++ examples and add Python examples

src/cufinufft.cu
I found recently that using `exp(sqrt())` instead of `Horner evaluation` for kernel evaluation gives better performance on Flatiron cluster:
e.g. (the last argument is to control the method of kernel evaluation, **0:** exp(sqrt()); **1:** Horner evaluation)
For spreading method 1 (GM-sort): 
bin/spread2d_test_32 1 0 256 256 1024 65536 1e-5 **1**
[Method 1] 65536 NU pts to #65536 U pts in 0.0024 s (2.74e+07 NU pts/s)
bin/spread2d_test_32 1 0 256 256 1024 65536 1e-5 **0**
[Method 1] 65536 NU pts to #65536 U pts in 0.000198 s (3.31e+08 NU pts/s)
For spreading method 2 (SM), the difference are smaller:
bin/spread2d_test_32 2 0 256 256 1024 65536 1e-5 **1**
[Method 2] 65536 NU pts to #65536 U pts in 0.00311 s (2.11e+07 NU pts/s)
bin/spread2d_test_32 2 0 256 256 1024 65536 1e-5 **0**
[Method 2] …
=> Change default method to evaluate kernel

Makefile
Here is one minor change we discussed to do -- remove the host compiler option `-g`.
=> remove -g flag

python/cufinufft/cufinufft.py
@MelodyShih , try this for #85 . I think this will let you keep your examples as they were. This should keep python from cleaning up the set_pts arrays before the cufinufft class instance is cleaned up. 
Closes #85
=> Hold a reference to set_pts gpuarrays in the class

ci/docker/cuda10.1/CentOS-SCLo-scl-rh.repo, ci/docker/cuda10.1/CentOS-SCLo-scl.repo, ci/docker/cuda10.1/Dockerfile-x86_64, ci/docker/cuda10.1/vault.repo
Redirects yum links to CentOS 6 vault.
This fixed up `ci/docker/cuda10.1/Dockerfile-x86_64` for me.
Closes #92
=> Updates for CentOS 6 deprecation

ci/build-wheels.sh, ci/distribution_helper.sh, ci/docker/cuda10.1/Dockerfile-x86_64, ci/docker/cuda11.0/Dockerfile-x86_64, targets/make.inc.manylinux
Add a `manylinux` target that downgrades the instruction set to SSE4 to increase compatibility. (We're (hopefully) not reliant on AVX(2) instructions for our performance, so this is not a big restriction.) We then use this target in the wheel-building scripts to make sure our binary wheels will run on older CPUs.
Also upgrades pip to remove those warnings.
=> Fix build wheels

.bumpversion.cfg, README.md, python/cufinufft/README.md, setup.py
Right now, our project description on PyPI is [quite terse](https://pypi.org/project/cufinufft/). This PR extends the description a little bit with helpful links, although there is more work to do here.
Also fixes up the author list, URLs, classifiers, and minimum Python version requirements.
=> Extend description in setup.py

ci/distribution_helper.sh
Since installing from an sdist requires cuFinufft to already be
installed (and present in `LIBRARY_PATH` and `LD_LIBRARY_PATH`), it's
simpler to only ship binary wheels and direct advanced users to install
directly from the source repository.
=> Remove sdist from distribution_helper.sh

src/2d/spreadinterp2d.cu, src/3d/spreadinterp3d.cu
This is related to #112 .
The error happens when nonuniform points lie on the fine grid. 
The distance between the point and the grid point are exactly `kernelwidth/2` and cause 
`exp(es_beta * (sqrt(1.0 - es_c*x*x)))` evaluates to `nan`. 
I added checks to enforce this does not happen.
=> Add checks to ensure distance is strictly less than half of kernel width

python/cufinufft/requirements.txt
With the transition from 1.21 to 1.22, NumPy is dropping the binary wheels for manylinux2010 and replacing them with manylinux2014. To make this work for now, we are downgrading NumPy to 1.21 in our requirements.
=> Fix NumPy installation

Makefile, README.md, include/cufinufft_eitherprec.h, src/1d/README, src/1d/cufinufft1d.cu, src/1d/interp1d_wrapper.cu, src/1d/spread1d_wrapper.cu, src/1d/spreadinterp1d.cu, src/2d/spreadinterp2d.cu, src/3d/spreadinterp3d.cu, src/cudeconvolve.h, src/cufinufft.cu, src/cuspreadinterp.h, src/deconvolve_wrapper.cu, src/memtransfer_wrapper.cu, src/precision_independent.cu, src/precision_independent.h, test/cufinufft1d1_test.cu, test/cufinufft1d2_test.cu, test/cufinufft2d2_test.cu, test/cufinufft3d2_test.cu, test/interp1d_test.cu, test/spread1d_test.cu
Methods implemented: 
- NUpts driven for both type 1 (spreading) and type 2 (interpolation)
- Subproblem for type 1. 
Test codes include one mode accuracy check and here are some example output:
```
./cufinufft1d1_test 1 1e6 1e6
[Method 1] 1000000 NU pts to 1000000 U pts in 0.0218 s:      4.59e+07 NU pts/s
(exec-only thoughput: 1.87e+08 NU pts/s)
[gpu   ] one mode: rel err in F[370000] is 8.7e-08
```
```
./cufinufft1d1_test 2 1e6 1e6
[Method 2] 1000000 NU pts to 1000000 U pts in 0.0198 s:      5.04e+07 NU pts/s
(exec-only thoughput: 2.17e+08 NU pts/s)
[gpu   ] one mode: rel err in F[370000] is 8.7e-08
```
```
./cufinufft1d2_test 1 1e6 1e6
[Method 1] 1000000 U pts to 1000000 NU pts in 0.0201 s:      4.98e+07 NU pts/s
(exec-only thoughput: 2.85e+08 NU pts/s)
[gpu   ] one targ: rel err in …
```
=> Add 1d support. 

Jenkinsfile
Looks like the current issue is that pycuda is compiled against a newer NumPy version (1.22) and then an older version (1.21) installed (following #121). This PR removes the `--system-site-packages` flag for the venv so that it ignores the previously installed (system-wide) packages and installs its own NumPy.
=> Attempt to fix Jenkins CI

contrib/common.h, contrib/dataTypes.h, src/cufinufft.cu, test/cufinufft1d1_test.cu, test/cufinufft2d1_test.cu, test/cufinufft2d1many_test.cu, test/cufinufft2d1nupts_test.cu, test/cufinufft3d1_test.cu
Thanks elliottslaughter reports the bug of casting an integer (MAX_NF) greater than INT_MAX to `int` (`BIGINT`) in #116.  The casted result will be implementation-defined.  
I adopt the suggestion of making MAX_NF as INT_MAX. 
I think this is an easier fix because I was not careful about using between `BIGINT` and `int`...:( If we want to use 64 bits integer, more changes need to be involved. For consistency, I removed the usage of `BIGINT` in cufinufft source codes and use `int` everywhere.
@ahbarnett, please let me know what do you think about this. Thanks!
=> modify MAX_NF and temporarily remove the usage of BIGINT in cufinufft source and test files

src/1d/spreadinterp1d.cu, src/2d/spreadinterp2d.cu, src/3d/spreadinterp3d.cu, src/cufinufft.cu
The interpolation kernels when `kernevalmeth = 0` was evaluating the kernel w^d times rather than w*d times as the spreading kernels do. This pull request fixes it. 
p.s. we changed the default value of `kernevalmeth` at some point and these changes should have been done then -- sorry about that.
Here are some performance results before (in the parenthesis) and after the change: 
| GPU | 2D | 3D |
| :---: | :---: | :---: |
| V100 | 1.9 ms (1.8 ms) | 4.0 ms (5.5 ms) |
| RTX8000 | 3.8 ms (6.1 ms)| 24.1 ms (81.0 ms)|
Commands for the tests -- 
`bin/interp2d_test 1 0 1024 1024 1048576 1e-3`
`bin/interp3d_test 1 0 128 128 128 2097152 1e-3`
This seems to have a smaller impact on V100. But on RTX8000, we see about 1.6x and 3.4x for the 2D and 3D test case, respectively.
=> Update ways to evaluate kernel value when using kerevalmeth=0 (i.e. exp(sqrt())) in interpolation kernels

Jenkinsfile
I noticed that `make check` is not being run in Jenkins. I'm adding it because I suspect there are failures in the test suite that aren't being caught at the moment.
=> Run make check in Jenkins

CHANGELOG, Makefile, contrib/common.cpp, contrib/common.h, include/cufinufft_eitherprec.h, src/1d/interp1d_wrapper.cu, src/2d/interp2d_wrapper.cu, src/3d/interp3d_wrapper.cu, src/common.cu, src/common.h, src/cufinufft.cu, src/precision_independent.cu, src/precision_independent.h, test/fseries_kernel_test.cu, test/fseriesperf.sh
The pull request adds a GPU implementation of the 2nd half of function `onedim_fseries_kernel()` and its relative test code and scripts (see [fseries_kernel_test.cu](https://github.com/MelodyShih/cufinufft/blob/onedim_fseries_kernel/test/fseries_kernel_test.cu) and [fseriesperf.sh](https://github.com/MelodyShih/cufinufft/blob/onedim_fseries_kernel/test/fseriesperf.sh)). 
The timing results (tol=1e-6) on a V100 GPU and a Intel Xeon Platinum 8268 CPU shows that it gives a speedup ranges from 0.8x to 27.3x:
According to this timing, I add a heuristic in `src/cufinufft.cu` to switch between the CPU version and the GPU version basing on `nf1`, `nf2` and `nf3`.
ps. the pull request also includes minor updates in the print statement of interpolation kernels.
=> GPU Implementation of 2nd half of onedim_fseries_kernel()

python/cufinufft/cufinufft.py
I found that some of the latest installs have been complaining about the base `if ...` checks.  This resolved for me locally so I'm offering it up here as a patch.
=> Less ambiguous None check for python ptrs
